In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Lab04_data.csv")
df

        Age  Income Student Credit_Rating Buys_Computer
0      <=30    high      no          fair            no
1      <=30    high      no     excellent            no
2   30---40    high      no          fair           yes
3       >40  medium      no          fair           yes
4       >40     low     yes          fair           yes
5       >40     low     yes     excellent            no
6   30---40     low     yes     excellent           yes
7      <=30  medium      no          fair            no
8      <=30     low     yes          fair           yes
9       >40  medium     yes          fair           yes
10     <=30  medium     yes     excellent           yes
11  30---40  medium      no     excellent           yes
12  30---40    high     yes          fair           yes
13      >40  medium      no     excellent            no

In [6]:
n = len(df)
count_yes = count_no = 0
for i in range(0,n):
    if df['Buys_Computer'][i] == "yes":
        count_yes += 1
    if df['Buys_Computer'][i] == "no":
        count_no += 1
probability_yes = count_yes/n
probability_no = count_no/n
print(probability_yes)
print(probability_no)

0.6428571428571429
0.35714285714285715

In [9]:
#A2
features = ['Age', 'Income', 'Student', 'Credit_Rating']
 
class_conditional_densities = {}
 
for feature in features:
    feature_probabilities = {}
    for label in df['Buys_Computer'].unique():
        class_data = df[df['Buys_Computer'] == label][feature]
        class_size = len(class_data)
        category_counts = {}
        for category in class_data:
            if category not in category_counts:
                category_counts[category] = 1
            else:
                category_counts[category] += 1
        probabilities = {category: count / class_size for category, count in category_counts.items()}
        feature_probabilities[label] = probabilities
 
    class_conditional_densities[feature] = feature_probabilities
 
    for feature, values in class_conditional_densities.items():
        print(f"\nClass Conditional Densities for {feature}:")
    for label, probabilities in values.items():
        print(f"Class {label}: {feature} probabilities: {probabilities}")

Class Conditional Densities for Age:
Class no: Age probabilities: {'<=30': 0.6, '>40': 0.4}
Class yes: Age probabilities: {'30---40': 0.4444444444444444, '>40': 0.3333333333333333, '<=30': 0.2222222222222222}

Class Conditional Densities for Age:

Class Conditional Densities for Income:
Class no: Income probabilities: {'high': 0.4, 'low': 0.2, 'medium': 0.4}
Class yes: Income probabilities: {'high': 0.2222222222222222, 'medium': 0.4444444444444444, 'low': 0.3333333333333333}

Class Conditional Densities for Age:

Class Conditional Densities for Income:

Class Conditional Densities for Student:
Class no: Student probabilities: {'no': 0.8, 'yes': 0.2}
Class yes: Student probabilities: {'no': 0.3333333333333333, 'yes': 0.6666666666666666}

Class Conditional Densities for Age:

Class Conditional Densities for Income:

Class Conditional Densities for Student:

Class Conditional Densities for Credit_Rating:
Class no: Credit_Rating probabilities: {'fair': 0.4, 'excellent': 0.6}
Class yes: Credit_Rating probabilities: {'fair': 0.6666666666666666, 'excellent': 0.3333333333333333}